export enum PrintActions {
  REPRINT_ONSITE_ORDER_TICKET = 'REPRINT_ONSITE_ORDER_TICKET',
  REPRINT_TOGO_ORDER_TICKET = 'REPRINT_TOGO_ORDER_TICKET',
  REPRINT_RAPPI_ORDER_TICKET = 'REPRINT_RAPPI_ORDER_TICKET',
  REPRINT_PHONE_ORDER_TICKET = 'REPRINT_PHONE_ORDER_TICKET',
  CONSOLIDATED_COMMAND_RESTAURANT = 'CONSOLIDATED_COMMAND_RESTAURANT',
  CONSOLIDATED_COMMAND_TOGO = 'CONSOLIDATED_COMMAND_TOGO',
  CONSOLIDATED_COMMAND_RAPPI = 'CONSOLIDATED_COMMAND_RAPPI',
  CONSOLIDATED_COMMAND_PHONE = 'CONSOLIDATED_COMMAND_PHONE',
  REPRINT_FOR_PAY_ORDER_ONSITE = 'REPRINT_FOR_PAY_ORDER_ONSITE',
  REPRINT_FOR_PAY_ORDER_TOGO = 'REPRINT_FOR_PAY_ORDER_TOGO',
  REPRINT_FOR_PAY_ORDER_RAPPI = 'REPRINT_FOR_PAY_ORDER_RAPPI',
  REPRINT_FOR_PAY_ORDER_PHONE = 'REPRINT_FOR_PAY_ORDER_PHONE',
}
